repos:
  # Pytest to run tests before commit
  - repo: https://github.com/pre-commit/pytest
    rev: v7.0.0
    hooks:
      - id: pytest
        args: ['--maxfail=1', '--disable-warnings', '--tb=short']  # Customize pytest args as needed

